sudo: required
language: node_js

node_js:
  - "8"

services:
  - docker

before_install:
  - docker build -t mitulgolakiya/docker-react -f Dockerfile.dev .

scripts:
  - docker run mitulgolakiya/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-236266540883"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"