sudo: required
language: node_js

node_js:
  - "8"

services:
  - docker

before_install:
  - docker build -t mitulgolakiya/docker-react -f Dockerfile.dev .

scripts:
  - docker run mitulgolakiya/docker-react npm run test -- --coverage